var data = {}


data.photo = [
  'asyncphotos/1.jpg',
  'asyncphotos/2.jpg',
  'asyncphotos/3.jpg',
  'asyncphotos/4.jpg',
  'asyncphotos/5.jpg',
  'asyncphotos/6.jpg',
  'asyncphotos/7.jpg',
  'asyncphotos/8.jpg',
  'asyncphotos/9.jpg',
  'asyncphotos/10.jpg',
  'asyncphotos/11.jpg',
  'asyncphotos/12.jpg',
  'asyncphotos/13.jpg',
  'asyncphotos/14.jpg',
  'asyncphotos/15.jpg',
  'asyncphotos/16.jpg',
  'asyncphotos/17.jpg',
  'asyncphotos/18.jpg',
  'asyncphotos/19.jpg',
  'asyncphotos/20.jpg',
  'asyncphotos/21.jpg',
  'asyncphotos/22.jpg',
  'asyncphotos/23.jpg',
  'asyncphotos/24.jpg',
  'asyncphotos/25.jpg',
  'asyncphotos/26.jpg',
  'asyncphotos/27.jpg',
  'asyncphotos/28.jpg',
  'asyncphotos/29.jpg',
  'asyncphotos/30.jpg',
  'asyncphotos/31.jpg',
  'asyncphotos/32.jpg',
  'asyncphotos/33.jpg',
  'asyncphotos/34.jpg',
  'asyncphotos/35.jpg',
  'asyncphotos/36.jpg',
  'asyncphotos/37.jpg',
  'asyncphotos/38.jpg',
  'asyncphotos/39.jpg',
  'asyncphotos/40.jpg',
  'asyncphotos/41.jpg',
  'asyncphotos/42.jpg',
  'asyncphotos/43.jpg',
  'asyncphotos/44.jpg',
  'asyncphotos/45.jpg',
  'asyncphotos/46.jpg',
  'asyncphotos/47.jpg',
  'asyncphotos/48.jpg',
  'asyncphotos/49.jpg',
  'asyncphotos/50.jpg'
];

data.cuisine = [
  "Cafe",
  "Dessert",
  "Vietnamese Food",
  "Middle Eastern Food",
  "Pizza",
  "Subs & Sandwiches",
  "Mediterranean",
  "Japanese Food",
  "Chicken",
  "Vegetarian",
  "Turkish Food",
  "Chinese",
  "Seafood",
  "Greek Food",
  "Pakistani Food",
  "Chinese Food",
  "Thai Food",
  "Spanish Food",
  "Moroccan",
  "Asian Food",
  "Halal",
  "Pakistani",
  "Indian Food",
  "Coffee & Tea",
  "Asian",
  "Grocery",
  "Sandwiches",
  "Vegan",
  "Mexican",
  "American",
  "Buffets",
  "Indian",
  "Vietnamese",
  "BBQ",
  "Latin American Food",
  "Mexican Food",
  "Deli",
  "Middle Eastern",
  "Pasta",
  "Jamaican Food",
  "Mediterranean Food",
  "Subs",
  "Ethnic Food",
  "Steak",
  "Bar/Pub Food",
  "Himalayan & Nepalese Food",
  "Catering",
  "Breakfast",
  "Asian Fusion",
  "Korean Food",
  "Hawaiian Food",
  "Japanese",
  "Burgers",
  "indian",
  "Sushi",
  "Italian Food",
  "Wings",
  "Shanghainese",
  "Thai",
  "Greek",
  "Gluten Free",
  "American Food",
  "MIddle Eastern"
]

data.diningStyle =
  ["Casual Dining", "Elegant Dining", "Elegant", "Casual Elegant"]
data.dressingStyle =
["Casual Dress", "Business Casual", "Tie and Suit"]
data.cuisine =
["Mediterranean", "Chinese", "French", "Japanese", "Italian", "American", "Thai","Vietnamese", "Mexican", "Iranian", "Persian", "Hawaiian"]

data.paymentOptions =
  ["AMEX", "Discover", "Visa", "MasterCard"]

module.exports = data;